"""Init

Revision ID: 06ad616f4c7b
Revises: 
Create Date: 2023-04-12 15:23:29.905948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06ad616f4c7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csgo_market_fourth_stage',
                    sa.Column('market_id', sa.String(), nullable=False),
                    sa.Column('market_hash_name', sa.String(), nullable=False),
                    sa.Column('price', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('asset', sa.String(), nullable=True),
                    sa.Column('class_id', sa.String(), nullable=True),
                    sa.Column('instance_id', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True)
                    )
    op.execute(
        'CREATE INDEX ix_csgo_market_fourth_stage_market_id ON csgo_market_fourth_stage USING HASH (market_id);')
    op.create_table('csgo_market_history',
                    sa.Column('market_hash_name', sa.String(), nullable=False),
                    sa.Column('time', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('price', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True)
                    )
    op.execute(
        'CREATE INDEX ix_csgo_market_history_market_hash_name ON csgo_market_history USING HASH (market_hash_name);')
    op.create_table('csgo_market_on_sale',
                    sa.Column('market_id', sa.String(), nullable=False),
                    sa.Column('market_hash_name', sa.String(), nullable=False),
                    sa.Column('asset', sa.String(), nullable=True),
                    sa.Column('class_id', sa.String(), nullable=False),
                    sa.Column('instance_id', sa.String(), nullable=False),
                    sa.Column('price', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True)
                    )
    op.execute(
        'CREATE INDEX ix_csgo_market_on_sale_market_id ON csgo_market_on_sale USING HASH (market_id);')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csgo_market_on_sale_market_id'), table_name='csgo_market_on_sale')
    op.drop_table('csgo_market_on_sale')
    op.drop_index(op.f('ix_csgo_market_history_market_hash_name'), table_name='csgo_market_history')
    op.drop_table('csgo_market_history')
    op.drop_index(op.f('ix_csgo_market_fourth_stage_market_id'), table_name='csgo_market_fourth_stage')
    op.drop_table('csgo_market_fourth_stage')
    # ### end Alembic commands ###
